/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package powpaw;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.input.KeyEvent;
import javafx.stage.Stage;
import powpaw.model.api.World;
import powpaw.model.impl.WorldImpl;
import powpaw.view.api.WorldRender;

public class App extends Application {
    private WorldRender worldRender = new WorldRender();
    private World world = new WorldImpl();

    public static void main(String[] args) {
        Application.launch(App.class, args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Scene worldScene = worldRender.createScene();
        worldScene.setOnKeyPressed(new EventHandler<KeyEvent>() {

            @Override
            public void handle(KeyEvent event) {
                world.getKeyObservable().notifyObservers(event);
                System.out.println(event.getCode());
            }
        });
        primaryStage.setTitle("PowPaw");
        primaryStage.setScene(worldScene);
        primaryStage.setResizable(false);
        primaryStage.show();
    }
}
